language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t emresonmezoglu/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true emresonmezoglu/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-west-1-668619479811"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access:key: $AWS_SECRET_KEY