language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t emresonmezoglu/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true emresonmezoglu/docker-react npm run test